In [2]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import os

In [3]:
## Loading data - an excell file :

data1 = pd.ExcelFile('Tranzact2.xlsx')
tranzact_data1 = data1.parse(0)

lamba = len(tranzact_data1)
print(lamba)
tranzact_data1.columns

28922


Index(['Company', 'Supplier', 'Item', 'Category', 'UOM', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [4]:
tranzact_data1.tail()

Company               Supplier  \
28917  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28918  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28919  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28920  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28921     Airbex System Pvt. Ltd          Anant Traders   

                                          Item              Category   UOM  \
28917                    Ferrul Number 4mm 'R'  Electrical Component   PKT   
28918                    Ferrul Number 4mm 'Y'  Electrical Component   PKT   
28919                    Ferrul Number 4mm 'B'  Electrical Component   PKT   
28920                    Ferrul Number 4mm 'N'  Electrical Component   PKT   
28921  7/8" Hard copper pipe 20 gauge 10' long         Raw Materials  Rmtr   

      Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  \
28917        NaN        NaN        NaN        NaN        NaN         NaN   
28918        NaN        NaN        NaN        NaN        NaN         NaN   
28919        NaN        NaN        NaN        NaN        NaN         NaN   
28920        NaN        NaN        NaN        NaN        NaN         NaN   
28921        NaN        NaN        NaN        NaN        NaN         NaN   

      Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16  
28917         NaN         NaN         NaN         NaN         NaN          NaN  
28918         NaN         NaN         NaN         NaN         NaN          NaN  
28919         NaN         NaN         NaN         NaN         NaN          NaN  
28920         NaN         NaN         NaN         NaN         NaN          NaN  
28921         NaN         NaN         NaN         NaN         NaN          NaN

In [5]:
tranzact_data2 = tranzact_data1.iloc[0:lamba, 0:3] ## Remove unnecessary columns

tranzact_data2['Item'] = tranzact_data2['Item'].map(lambda x: x if type(x)!=str else x.lower()) ## make Items in lower case


tranzact_data = tranzact_data2.dropna() ## remove rows with cell value none

tranzact_data = tranzact_data.reset_index(drop=True)
print(len(tranzact_data))
print(tranzact_data['Item'][9938])

print(type(tranzact_data['Item']))
print(type(tranzact_data['Item'][9938]))
      
tranzact_data.tail()
#tranzact_data.info()

28921
4)
<class 'pandas.core.series.Series'>
<class 'str'>


Company               Supplier  \
28916  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28917  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28918  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28919  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28920     Airbex System Pvt. Ltd          Anant Traders   

                                          Item  
28916                    ferrul number 4mm 'r'  
28917                    ferrul number 4mm 'y'  
28918                    ferrul number 4mm 'b'  
28919                    ferrul number 4mm 'n'  
28920  7/8" hard copper pipe 20 gauge 10' long

In [6]:
## Cleaning the Item Description to create a feature matrix :

pd.options.mode.chained_assignment = None
print(tranzact_data['Item'][9938])

tranzact_data['features'] = tranzact_data['Item'].str.replace(r'\b\d+\b','')  ## remove integers
print(tranzact_data['features'][9938])

tranzact_data['features'] = tranzact_data['features'].str.replace(r'\W',' ')   ## remove puntuations
print(tranzact_data['features'][9938])

tranzact_data['features'] = tranzact_data['features'].str.replace(r'\b\d+\mm\b',' ')   ## remove all 'mm' dimensions only
print(tranzact_data['features'][9938])

tranzact_data['features'] = tranzact_data['features'].str.replace(r'\b\w\b','') ## remove stand alone single letters
print(tranzact_data['features'][9938])

tranzact_data['features'] = tranzact_data['features'].str.replace(r'\s+',' ', flags = re.I) ## remove gaps between words to singe gap
print(tranzact_data['features'][9938])


## Removing unneccessary words like measurment units etc.
                                                                        
words = stopwords.words("english")

words.append('mm')
words.append('ft')
words.append('as')
words.append('to')
words.append('nos')

tranzact_data['features']= tranzact_data['features'].apply(lambda x:' '.join([i for i in x.split()
                                                                                if i not in words]).lower())
print(tranzact_data['features'][5])

print(len(tranzact_data))
#tranzact_data.tail()


4)
)
 
 
 
 
ms sheet
28921


In [7]:
for i in range(len(tranzact_data)):
    if tranzact_data['features'][i] == '':
        
        tranzact_data['Supplier'][i] = np.nan
    
        
tranzact_data = tranzact_data.dropna()
tranzact_data = tranzact_data.reset_index(drop=True)

print(len(tranzact_data))

tranzact_data.tail()


28913


Company               Supplier  \
28908  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28909  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28910  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28911  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28912     Airbex System Pvt. Ltd          Anant Traders   

                                          Item                     features  
28908                    ferrul number 4mm 'r'                ferrul number  
28909                    ferrul number 4mm 'y'                ferrul number  
28910                    ferrul number 4mm 'b'                ferrul number  
28911                    ferrul number 4mm 'n'                ferrul number  
28912  7/8" hard copper pipe 20 gauge 10' long  hard copper pipe gauge long

In [8]:
## To check no. of Suppliers & no. of unique featuresin the data base :

print('Supplier = ', len(tranzact_data.Supplier.value_counts()))
print('Unique Features = ', len(tranzact_data.features.value_counts()))
print('Tranzact_data length = ', len(tranzact_data))
tranzact_data.tail()

Supplier =  2337
Unique Features =  16727
Tranzact_data length =  28913


Company               Supplier  \
28908  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28909  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28910  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28911  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
28912     Airbex System Pvt. Ltd          Anant Traders   

                                          Item                     features  
28908                    ferrul number 4mm 'r'                ferrul number  
28909                    ferrul number 4mm 'y'                ferrul number  
28910                    ferrul number 4mm 'b'                ferrul number  
28911                    ferrul number 4mm 'n'                ferrul number  
28912  7/8" hard copper pipe 20 gauge 10' long  hard copper pipe gauge long

In [7]:
## Above indicates that there are 2337 suppliers supplying 28921 items(as per no. of rows)
## above indicates that there are 16728 unique features out of 28921 items(as per rows)

In [8]:
## Let's reduce no. of Suppliers : criterian - apperaing at least 10 times in the data frame

# tranzact_data_short = tranzact_data.groupby("Supplier").filter(lambda x: len(x) > 10)

# print(len(tranzact_data_short))
# print(len(tranzact_data_short.Supplier.value_counts()))

In [9]:
## Above indicates that there are now 391 suppliers supplying 23649 items(as per no. of rows)

In [9]:
## Removing duplicate features + Supplier combinations :

for i in range (len(tranzact_data)):
    
    idx_feature = []
    idx_Supplier = []
    idx_common = []

    idx_feature = tranzact_data.index[tranzact_data['features'] == tranzact_data['features'][i]].tolist()
    idx_Supplier = tranzact_data.index[tranzact_data['Supplier'] == tranzact_data['Supplier'][i]].tolist()
    idx_common = list(set(idx_feature).intersection(idx_Supplier))
    
    if len(idx_common) > 1:
        
        tranzact_data['Supplier'][idx_common[1:]] = np.nan
        
tranzact_data_final = tranzact_data.dropna()
tranzact_data_final = tranzact_data_final.reset_index(drop=True) 
        
# tranzact_data = tranzact_data.drop(tranzact_data.index[idx_common[j]][1:])
                   

In [10]:
## To cross check no. of Suppliers & no. of unique features in the data base :

print('Supplier = ', len(tranzact_data_final.Supplier.value_counts()))
print('Unique Features = ', len(tranzact_data_final.features.value_counts()))
print('Total no. of entrys = ', len(tranzact_data_final))
tranzact_data_final.tail()

Supplier =  2337
Unique Features =  16727
Total no. of entrys =  19761


Company               Supplier  \
19756  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
19757  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
19758  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
19759  Polfrost Air Con Pvt Ltd.  M/S. S. K. Enterprise   
19760     Airbex System Pvt. Ltd          Anant Traders   

                                          Item                     features  
19756                           pvc gland pg11               pvc gland pg11  
19757                         pvc gland pg13.5               pvc gland pg13  
19758                        pvc gland m25x1.5              pvc gland m25x1  
19759                    ferrul number 1mm '1'                ferrul number  
19760  7/8" hard copper pipe 20 gauge 10' long  hard copper pipe gauge long

In [11]:
col = ['Supplier', 'features']
tranzact_data_search = tranzact_data_final[col]


tranzact_data_search['Supplier_id'] = tranzact_data_search['Supplier'].factorize()[0]  ## Indexing

supplier_id_tranzact_data_search = tranzact_data_search[['Supplier', 'Supplier_id']].drop_duplicates(). \
                                                        sort_values('Supplier_id')

## Create two dictionaries :

supplier_to_id = dict(supplier_id_tranzact_data_search.values)
id_to_supplier = dict(supplier_id_tranzact_data_search[['Supplier_id', 'Supplier']].values)

supplier_id_tranzact_data_search.head()



Supplier  Supplier_id
0        Pukhraj Additives LLP            0
2                 Bijal Steels            1
3  Jay Khodiyar Steel & Metals            2
4           Dynachem Engineers            3
6            Sharp Engineering            4

In [12]:

print(len(supplier_id_tranzact_data_search))
supplier_id_tranzact_data_search.tail()

2337


Supplier  Supplier_id
19741                           S C Industrial Syndicate         2332
19742                     Maxell Heat Exchangers Pvt Ltd         2333
19746         Imerys Minerals Malaysia Sdn Bhd (86796-M)         2334
19750                              Sigma Roto Lining LLP         2335
19751  Guangdong Yuxing Fire-retardant New Materials ...         2336

In [13]:
tranzact_data_search.tail()

Supplier                     features  Supplier_id
19756  M/S. S. K. Enterprise               pvc gland pg11          312
19757  M/S. S. K. Enterprise               pvc gland pg13          312
19758  M/S. S. K. Enterprise              pvc gland m25x1          312
19759  M/S. S. K. Enterprise                ferrul number          312
19760          Anant Traders  hard copper pipe gauge long         2135

In [14]:
# Digitising Process No. 1

from sklearn.feature_extraction.text import TfidfVectorizer

# create the transform
my_vectorizer = TfidfVectorizer()

# tokenize and build vocab
digital_features = my_vectorizer.fit(tranzact_data_search['features'])
# summarize
# print(my_vectorizer.vocabulary_)

# encode document
my_vector = digital_features.transform(tranzact_data_search['features']).toarray()
# summarize encoded vector
print(my_vector.shape)

print(len(my_vector))

print(my_vector)

print(max(my_vector[0]))

(19761, 13421)
19761
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.8110634360883946


In [14]:
## Digitising Process No. 2 : same as above but slightly different syntax

from sklearn.feature_extraction.text import TfidfVectorizer

#tfidf = TfidfVectorizer(sublinear_tf=True, min_df=2, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')
#features = tfidf.fit_transform(df.Consumer_complaint_narrative).toarray()

#features.shape

my_tfidf = TfidfVectorizer()
digit_features = my_tfidf.fit_transform(tranzact_data_search.features).toarray()

print(digit_features.shape)

print(digit_features)


(19761, 13421)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## 
* sublinear_df is set to True to use a logarithmic form for frequency.
* min_df is the minimum numbers of documents a word must be present in to be kept.
* norm is set to l2, to ensure all our feature vectors have a euclidian norm of 1.
* ngram_range is set to (1, 2) to indicate that we want to consider both unigrams and bigrams.
* stop_words is set to "english" to remove all common pronouns ("a", "the", ...) to reduce the number of noisy * * * features.


In [15]:
## Digitising Process No. 3

my_my_tfidf = TfidfVectorizer(sublinear_tf=True, min_df=2, norm='l2', encoding='latin-1', \
                        ngram_range=(1, 2), stop_words='english')
dig_features = my_my_tfidf.fit_transform(tranzact_data_search.features).toarray()

print(dig_features.shape)
print(dig_features)


(19761, 16851)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
## Digitising Process No. 4

from sklearn.feature_extraction.text import HashingVectorizer

y_my_vectorizer = HashingVectorizer(n_features=50)

y_my_vector = y_my_vectorizer.transform(tranzact_data_search['features'])

print(y_my_vector.shape)
#print((y_my_vector.toarray())[300:305,:])
print(y_my_vector.toarray())


(19761, 50)
[[ 0.          0.70710678  0.         ...  0.          0.
   0.        ]
 [ 0.          0.70710678  0.         ...  0.          0.
   0.        ]
 [ 0.          0.         -0.31622777 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.         -0.4472136  ...  0.          0.
   0.        ]]


In [15]:
from math import*
 
def square_rooted(x):
 
    return round(sqrt(sum([a*a for a in x])),3)
 
def cosine_similarity(x,y):
 
    numerator = sum(a*b for a,b in zip(x,y))
    denominator = square_rooted(x)*square_rooted(y)
    return round(numerator/float(denominator),3)

In [16]:
text_data = ['spring steel coil']
text_data1 = pd.Series(text_data)
print(type(text_data1))

<class 'pandas.core.series.Series'>


In [17]:
pd.options.mode.chained_assignment = None

text_data_feature = text_data1.str.replace(r'\b\d+\b','')  ## remove integers

text_data_feature = text_data_feature.str.replace(r'\W',' ')   ## remove puntuations

text_data_feature = text_data_feature.str.replace(r'\b\d+\mm\b',' ')   ## remove all 'mm' dimensions only

text_data_feature = text_data_feature.str.replace(r'\b\w\b','') ## remove stand alone single letters

text_data_feature = text_data_feature.str.replace(r'\s+',' ') ## remove gaps between words to singe gap


## Removing unneccessary words like measurment units etc.
                                                                        
words = stopwords.words("english")

words.append('mm')
words.append('ft')
words.append('as')
words.append('to')
words.append('nos')

text_data_feature = text_data_feature.apply(lambda x:' '.join([i for i in x.split()
                                                                                if i not in words]).lower())
print(text_data_feature)

0    spring steel coil
dtype: object


In [20]:
merge_text_feature = []
merge_text_feature_digit = []
merge_digit_vector = []
test_digit_vector = []

merge_text_feature = tranzact_data_search['features'].append(pd.Series(text_data_feature))

merge_text_feature = merge_text_feature.reset_index(drop=True)

merge_text_feature_digit = my_vectorizer.fit(merge_text_feature)

# encode document
merge_digit_vector = merge_text_feature_digit.transform(merge_text_feature).toarray()


test_digit_vector = merge_digit_vector[len(merge_digit_vector)-1].reshape((merge_digit_vector.shape)[1],)

print(cosine_similarity(my_vector[19760], test_digit_vector))
print(max(my_vector[19760]))

c_s = []

for i in range(len(my_vector)):
    
    c_s.append(cosine_similarity(my_vector[i], test_digit_vector))

print(len(c_s))


print(type(c_s))


 
print(max(c_s))


0.0
0.5141972485381479
19761
<class 'list'>
0.623


In [21]:
print(c_s)

[0.0, 0.0, 0.298, 0.0, 0.0, 0.0, 0.0, 0.276, 0.276, 0.571, 0.623, 0.623, 0.623, 0.623, 0.623, 0.623, 0.623, 0.623, 0.479, 0.479, 0.294, 0.294, 0.298, 0.298, 0.298, 0.279, 0.279, 0.282, 0.282, 0.282, 0.282, 0.282, 0.263, 0.297, 0.281, 0.262, 0.298, 0.298, 0.298, 0.282, 0.282, 0.282, 0.297, 0.297, 0.297, 0.281, 0.281, 0.281, 0.276, 0.276, 0.292, 0.277, 0.277, 0.486, 0.486, 0.486, 0.486, 0.486, 0.469, 0.523, 0.523, 0.524, 0.281, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.267, 0.267, 0.267, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.186, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [24]:
#non_zero_matches = list(filter(lambda a: a != 0, c_s))

print(np.argsort(c_s)[-10:])

max_c_s_index = np.argsort(c_s)[-10:][::-1]

print('max index = ', max_c_s_index)

for k in range(len(max_c_s_index)):
    
    if tranzact_data_search['Supplier_id'][max_c_s_index[k]] \
                 == tranzact_data_search['Supplier_id'][max_c_s_index[k+1]]:
        
        max_c_s_index = np.delete(max_c_s_index, k)
                
    if k == len(max_c_s_index)-2:
        
        break
        

kount = 0

if c_s[max_c_s_index[0]] < 0.5:
    
    print('There are No suppliers for this item')
    
else:
    
    for i in range(len(max_c_s_index)):
        
        if c_s[max_c_s_index[i]] < 0.5:
            
            print('There are No more Suppliers')
                
            break
            
        print(tranzact_data_search['Supplier'][max_c_s_index[i]])            
        kount = kount+1
            
        if kount == 5 :
            break



[2171 1497   15   17   11   12   13   14   16   10]
max index =  [  10   16   14   13   12   11   17   15 1497 2171]
Manisha Wires Pvt. Ltd.
Jainex Limited
Bharat Steel Yard
International Industrial Spring
Superdrawn Wire Industries Pvt Ltd.


In [119]:
from sklearn.metrics.pairwise import cosine_similarity

# print(cosine_similarity([[1, 0, -1, 0]], [[-1,-1, 0]]))

# print(my_vector[0])

# cosine_similarity([my_vector[0]], [text_vector])
