In [37]:
import tensorflow as tf
import pandas as pd
import numpy as np
import scipy
import sklearn
import os

In [38]:
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [39]:
observations = 10

xs = np.random.uniform(low = -10, high = 10, size = (observations,1))
zs = np.random.uniform(low = -10, high = 10, size = (observations,1))

generated_inputs = np.column_stack((xs, zs))
noise = np.random.uniform(low = -1, high = 1, size = (observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

# Now we want a format that can store the info in tensors. One of the way is to create .npz files. This is \
# good to save from a excell file or csv file, may not be required here where we have generated arrays

np.savez('TF_intro_data', my_inputs = generated_inputs, my_targets = generated_targets)


In [40]:
my_npzfile = np.load('TF_intro_data.npz') # pl. note that while loading(i.e. np.load), we should write the \
                                          # file name along with .npz
print(my_npzfile['my_inputs'])
print(my_npzfile['my_inputs'].shape)
print(type(my_npzfile['my_inputs']))
print('============================')

print(generated_inputs.shape)
print(type(generated_inputs))
print(generated_inputs)

[[-0.2689224  -9.75199274]
 [ 6.38644751 -7.54109515]
 [ 2.06626695  0.66216665]
 [ 4.23077192 -2.82074197]
 [ 1.1624892  -3.56214096]
 [ 2.33508934  1.06724794]
 [ 9.63307616  9.08846083]
 [-0.84646136 -7.71584586]
 [ 3.60830036 -2.80593004]
 [ 6.78579551  0.71308766]]
(10, 2)
<class 'numpy.ndarray'>
(10, 2)
<class 'numpy.ndarray'>
[[-0.2689224  -9.75199274]
 [ 6.38644751 -7.54109515]
 [ 2.06626695  0.66216665]
 [ 4.23077192 -2.82074197]
 [ 1.1624892  -3.56214096]
 [ 2.33508934  1.06724794]
 [ 9.63307616  9.08846083]
 [-0.84646136 -7.71584586]
 [ 3.60830036 -2.80593004]
 [ 6.78579551  0.71308766]]


In [41]:
# Below is just another example of how to save data in .npz file
arr1 = np.arange(8).reshape(2,4)
arr2 = np.arange(10).reshape(2,5)
np.savez('mat', name1 = arr1, name2 = arr2)

data = np.load('mat.npz')
print(data['name1'])
print(data['name2'])

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
observations = 1000

xs = np.random.uniform(low = -10, high = 10, size = (observations,1))
zs = np.random.uniform(low = -10, high = 10, size = (observations,1))

generated_inputs = np.column_stack((xs, zs))
noise = np.random.uniform(low = -1, high = 1, size = (observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

# Now we want a format that can store the info in tensors. One of the way is to create .npz files. This is \
# good to save from a excell file or csv file, may not be required here where we have generated arrays

np.savez('TF_intro_data', my_inputs = generated_inputs, my_targets = generated_targets)

In [63]:
Number_input_variable = 2  # xs and zs
Number_output = 1  # generated_targets

# INPUTS :

x1 = tf.placeholder(tf.float32, [None, Number_input_variable]) #this creates a matrix x of size observations(due to \
                                                            # 'None') X Number_input_variables
# my_inputs = tf.placeholder(tf.float32, [None, Number_input_variable])
# my_targets = tf.placeholder(tf.float32, [None, Number_output])

y = tf.placeholder(tf.float32, [None, Number_output])

# PARAMETERS :

weights = tf.Variable(tf.random_uniform([Number_input_variable, Number_output], minval = -0.1, maxval = 0.1))
biases = tf.Variable(tf.random_uniform([Number_output], minval = -0.1, maxval = 0.1))

# OUTPUTS :

y_hat = tf.matmul(x1, weights) + biases
# y_hat = tf.matmul(my_inputs, weights) + biases

# Objective Function :

mean_loss = tf.losses.mean_squared_error(labels = y, predictions = y_hat) / 2.
# mean_loss = tf.losses.mean_squared_error(labels = my_targets, predictions = y_hat) / 2.

# Optimizer :

optimize = tf.train.GradientDescentOptimizer(learning_rate = 0.05).minimize(mean_loss)

In [64]:
sess = tf.Session()
initializer = tf.global_variables_initializer()
sess.run(initializer)

In [65]:
print(weights)
print(biases)

<tf.Variable 'Variable_20:0' shape=(2, 1) dtype=float32_ref>
<tf.Variable 'Variable_21:0' shape=(1,) dtype=float32_ref>


In [66]:
train_data = np.load('TF_intro_data.npz')
print(train_data['my_inputs'])
x1 = train_data['my_inputs']
y = train_data['my_targets']

[[ 7.78993862  2.84629836]
 [ 2.46812871  4.41876478]
 [-7.40009082  5.78817723]
 ...
 [ 1.57951353  0.21396629]
 [ 4.38851842 -2.88746595]
 [ 4.30633729 -6.47753082]]


In [69]:

for e in range(100):        
        
    _, curr_loss = sess.run([optimize, mean_loss], feed_dict = {x1:train_data['my_inputs'], y:train_data['my_targets']})
    print(curr_loss)

TypeError: unhashable type: 'numpy.ndarray'